version: '3.8'

services:

  bmr:
    image: ${docker_registry}/bmr:latest
    container_name: bmr
    network_mode: host
    restart: unless-stopped
    # ports:
    #   - 6060:6060 # golang pprof
    entrypoint: ["/bin/bash", "-c"]
    command:
    - |
      echo '$bmr_config_json' >/config.json
      /bin/btpsimple -config /config.json
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}